version: '3.1'

services:

  db:
    image: postgis/postgis
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - db

  osm2pqsql:
    build:
      context: ./osm2pqsql
    depends_on: 
      - db