version: '3.1'

services:
  db:
    hostname: db
    image: postgis/postgis
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"
    command: postgres -c shared_buffers=1GB -c work_mem=50MB -c maintenance_work_mem=5GB -c wal_level=minimal -c checkpoint_timeout=60min -c max_wal_size=5GB -c checkpoint_completion_target=0.9 -c max_wal_senders=0 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - db

  osm2pqsql:
    image: cygnusolor/osm2pqsql:latest
    # build:
    #   context: ./osm2pqsql
    volumes: 
      - planet:/planet
    env_file:
       - .env
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind,delegated
  planet:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/planet
      o: bind,delegated



